spring.application.name=Movie
server.port=${PORT}

spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.base-url=${APP_BASE_URL:https://movie-manager-production.up.railway.app}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE:true}
spring.mail.properties.mail.smtp.starttls.required=${MAIL_STARTTLS_REQUIRED:true}
spring.mail.properties.mail.smtp.ssl.enable=${MAIL_SSL_ENABLE:false}
spring.mail.properties.mail.smtp.ssl.trust=${MAIL_SSL_TRUST:smtp.gmail.com}
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_CONNECTION_TIMEOUT:15000}
spring.mail.properties.mail.smtp.timeout=${MAIL_TIMEOUT:15000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_WRITE_TIMEOUT:15000}

logging.level.org.springframework.mail=DEBUG
logging.level.org.springframework.mail.javamail=DEBUG