spring.application.name=Movie
server.port=7019

spring.datasource.url=jdbc:postgresql://localhost:5432/movie_db
spring.datasource.username=movie_user
spring.datasource.password=movie_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
