spring.application.name=Movie
server.port=${PORT:7019}  # <-- use $PORT for Railway, 7019 is fallback for local dev

spring.datasource.url=jdbc:postgresql://<RAILWAY_DB_HOST>:<RAILWAY_DB_PORT>/<RAILWAY_DB_NAME>
spring.datasource.username=<RAILWAY_DB_USER>
spring.datasource.password=<RAILWAY_DB_PASS>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect